$axure.loadCurrentPage({
  "url":"order-accepted.html",
  "generationDate":new Date(1409664629253.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1a5fa57fb399449d988ebde9c3c8b298",
    "type":"Axure:Page",
    "name":"order-accepted",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"43",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setPanelState",
                "description":"Set Header/bucket to State2 fade out 500ms fade in 500ms",
                "panelsToStates":[{
                    "panelPath":["554cab938fd24941ba87a0ca1d2cdc87",
"55317add537e442a944eab57d304f251"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":2,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":false,
                      "options":{
                        "animateOut":{
                          "easing":"fade",
                          "duration":500},
                        "animateIn":{
                          "easing":"fade",
                          "duration":500},
                        "compress":false}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"554cab938fd24941ba87a0ca1d2cdc87",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fdae7ed1a7a54530b5f4cecce3fbfa3f"},
{
          "id":"830f6a44e5894f19be6af482e54ff6b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":301,
              "y":420},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce4d32935337479291854abc5b8aa7f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":301,
                  "y":420},
                "size":{
                  "width":200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df42d89f9b7d401f95dfe734bbed2399",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":86,
              "y":424},
            "size":{
              "width":184,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2306fbc5269f40fd9faadfc887d0953c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF91ABC8,
                  "opacity":1},
                "location":{
                  "x":86,
                  "y":424},
                "size":{
                  "width":184,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c4fb594aba346cd8375e6ab9de6f714",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":428},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u96_line.png"}},
{
          "id":"fc3f10c79c874be4a844547d59cfac53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Полужирный', 'Tahoma'",
            "location":{
              "x":90,
              "y":464},
            "size":{
              "width":800,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3f87361095d400b9a846c87380ca7c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Полужирный', 'Tahoma'",
                "location":{
                  "x":90,
                  "y":464},
                "size":{
                  "width":800,
                  "height":126}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22520588882344f48f9b0ecb28101f5c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":737},
            "size":{
              "width":818,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/buy/u49_line.png"}},
{
          "id":"4b1406026a6d42848108380a5f62f026",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Oblique', 'Tahoma'",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":72,
              "y":711},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7521008274ae4d6a9ef15e7ca6b2cc02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Oblique', 'Tahoma'",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":72,
                  "y":711},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open About in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"about.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf646c9879ec423eadafb91ed80b40fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Oblique', 'Tahoma'",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":160,
              "y":711},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d20086156775402a9a8311ad616edaf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Oblique', 'Tahoma'",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":160,
                  "y":711},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Payment in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"payment.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99d7dde72986415187170ac9cedbb0c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Oblique', 'Tahoma'",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":290,
              "y":711},
            "size":{
              "width":56,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd49dddc6a4c475cb4d00edfa2b53a6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Oblique', 'Tahoma'",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":711},
                "size":{
                  "width":56,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Contacts in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"contacts.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19a4041cd6394f9693e09401e233ec24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF768FA8,
              "opacity":1},
            "location":{
              "x":660,
              "y":711},
            "size":{
              "width":230,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4387524a14df4cb3b157f3e00a42d8d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF768FA8,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":711},
                "size":{
                  "width":230,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2237c3c92f9a477e88aa5209f3824c8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "location":{
              "x":72,
              "y":757},
            "size":{
              "width":296,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f861455366da47218efb5ab2d8730e97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "location":{
                  "x":72,
                  "y":757},
                "size":{
                  "width":296,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d00821ab14f41c187c26ebd0227c950",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "horizontalAlignment":"right",
            "location":{
              "x":660,
              "y":757},
            "size":{
              "width":230,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61a8e7ff202342ffaf5dca5c9ebfd2d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "horizontalAlignment":"right",
                "location":{
                  "x":660,
                  "y":757},
                "size":{
                  "width":230,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fd7c6773eb54599a0ab93d04032f492",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF768FA8,
              "opacity":1},
            "location":{
              "x":90,
              "y":597},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d231036358a4f419544eebea5f6fc99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF768FA8,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":597},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"396f66f7f2e44f6c9446cfecf92dbae5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":627},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66e5f463706a48019900682f2d8234b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":627},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u211.png"}},
{
          "id":"63c2de10cb554d9b91e9552e8c18e764",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":627},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b73086be9cd6487684b400619ab5c2e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":627},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u211.png"}},
{
          "id":"dc07e30f8c6b4e2a88f345cb3971f5ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":627},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c31a9690bb94f04bbf1dbc11627c007",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":627},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u211.png"}},
{
          "id":"ef9abde5354a43b4a040215710a92bac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":627},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9acdda4f3734be4a610b249b1086a6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":627},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u211.png"}},
{
          "id":"0f328a3870af4848ab4dc8f103fed504",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":384,
              "y":597},
            "size":{
              "width":210,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abc4b8054f8043cfad35576fc487be16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":384,
                  "y":597},
                "size":{
                  "width":210,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96e8fde9109b4e19984f6e043eeef63a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF768FA8,
              "opacity":1},
            "location":{
              "x":734,
              "y":597},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eb0bdf964a3460e991f3ae385b3c333",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF768FA8,
                  "opacity":1},
                "location":{
                  "x":734,
                  "y":597},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a35d1986f83544888a6c76f8eecc96a3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":389,
              "y":635},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/buy/u78_image_sketch.png",
            "disabled~":"images/buy/u78_disabled.png"}},
{
          "id":"f9b6461be08e44168ee550a1d8a8cdab",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":566,
              "y":635},
            "size":{
              "width":28,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/elefan/u224_image_sketch.png",
            "disabled~":"images/elefan/u224_disabled.png"}},
{
          "id":"ed1bc104055c45b8afd76ca3169e21ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":734,
              "y":637},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb1302739c194ee5a75f5ad88e99704c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":734,
                  "y":637},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u225.png"}},
{
          "id":"4b951842481f45f98fb14b310135f60a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":764,
              "y":637},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"238665adb09740caabd277f3cd2b48da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":764,
                  "y":637},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u225.png"}},
{
          "id":"51903c2138594e239ca2b98fb89204f4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":793,
              "y":637},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a6bfb0020c24c6f95f1396746a72679",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":793,
                  "y":637},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u225.png"}},
{
          "id":"4d825f195d654142a401a2d673e11c6d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":823,
              "y":637},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8674b82a8c54261a33f3cee3f032262",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":823,
                  "y":637},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u225.png"}},
{
          "id":"321f4f324433488c8a325113d629116d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":853,
              "y":637},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28227a5d87df4ea181908f395b0e3acf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":853,
                  "y":637},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u225.png"}}]}},
  "masters":{
    "fdae7ed1a7a54530b5f4cecce3fbfa3f":{
      "packageId":"fdae7ed1a7a54530b5f4cecce3fbfa3f",
      "type":"Axure:Master",
      "name":"Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7a656bc70beb4cebbb674e1988d4ccb9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":650,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1550a7031d74549a5e3808fe28523dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":650,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"9a64193b359b4c5687c040ea64ab310a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":410,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5cfaf345bfe4457091303fdad238b98e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":410,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"c2fa319619ec41e39d10aee62ddb8138",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9d01a4d23d5b4b1fac75e0903a85807d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Catalog in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"catalog.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"0995ce6a56be4ebf8696cfcf5ca75c1f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD9E2EC},
              "location":{
                "x":70,
                "y":320},
              "size":{
                "width":820,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b06c0da3b5a94376a4702acc7e084e31",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD9E2EC},
                  "location":{
                    "x":70,
                    "y":320},
                  "size":{
                    "width":820,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u7.png"}},
{
            "id":"58d46532d08b497c90742a6a133b2265",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":150,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"65cd6803d6c74eada90e7cc5f192f6bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":150,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Catalog in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"catalog.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/buy/u9.png"}},
{
            "id":"68872e9f4165442ebcb39fe8fa985046",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":390,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d5698240ae0421e80a86a8b304f76f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":390,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u9.png"}},
{
            "id":"2745e76898374f108fd8cd9b8748526f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":630,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9e7abb7fc60344e497c13195a317e074",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":630,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u9.png"}},
{
            "id":"9e2c0346349c476bbc513a00520db92d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":342},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cedf53687e4e4ea191ef703b28181fd0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":342},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u15.png"}},
{
            "id":"1958f2ebcc884dbf835c764dd1e0632e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF14472,
                "opacity":1},
              "location":{
                "x":410,
                "y":14},
              "size":{
                "width":140,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"28c2a1a9c2754fb5bee218a2350f544e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF14472,
                    "opacity":1},
                  "location":{
                    "x":410,
                    "y":14},
                  "size":{
                    "width":140,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Elefan in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"elefan.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"095b25becc6a48e182e319ce869cfc12",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":394.5,
                "y":110},
              "size":{
                "width":171,
                "height":25}},
            "adaptiveStyles":{
},
            "images":{
              "normal~":"images/buy/u19_image_sketch.png",
              "disabled~":"images/buy/u19_disabled.png"}},
{
            "id":"f742296fd5ba4d319cc333eefe7c3860",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":110},
              "size":{
                "width":25,
                "height":25}},
            "adaptiveStyles":{
},
            "images":{
              "normal~":"images/elefan/u20_image_sketch.png",
              "disabled~":"images/elefan/u20_disabled.png"}},
{
            "id":"5688d6e12fca40bc82107435ade74fae",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":324,
                "y":70},
              "size":{
                "width":82,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"820ce519720c49cba7e04c3f8a67733a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":324,
                    "y":70},
                  "size":{
                    "width":82,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d52df4ad408c474184b0f50a9f5242c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":424,
                "y":70},
              "size":{
                "width":132,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c95cea01d0c542c38bb50a2ad316f282",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":424,
                    "y":70},
                  "size":{
                    "width":132,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Payment in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"payment.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7ba4c045bc86427bb3bec19d485445a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":566,
                "y":70},
              "size":{
                "width":70,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df3e28c35f4b4161b72bd4f4c99b9907",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":566,
                    "y":70},
                  "size":{
                    "width":70,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9d9b62fd3b5741d1a1de543a9481fbb4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":660,
                "y":26},
              "size":{
                "width":230,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fbcce5ff719d4a6ca2c0ffaf89f8c834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":660,
                    "y":26},
                  "size":{
                    "width":230,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f317dfa0e23f4065956c33d8c541073b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":28},
              "size":{
                "width":32,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3bb420b31ba44460b717cc338975b06e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":28},
                  "size":{
                    "width":32,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u29.png"}},
{
            "id":"2eaf40de2dee4350bde1920c18dcf0be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":132,
                "y":26},
              "size":{
                "width":148,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4debd93021d842c389c5c56e4e285d99",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":132,
                    "y":26},
                  "size":{
                    "width":148,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"55317add537e442a944eab57d304f251",
            "label":"bucket",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":132,
                "y":45},
              "size":{
                "width":148,
                "height":22}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Buy in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"buy.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"618cad80e4c7413b886dfb19397c0e88",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"07cb8e47c26449eab6398fef68b744cc",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "size":{
                        "width":148,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6f2f8cacfa564d7980a579bd3e51eae0",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "size":{
                            "width":148,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"ec420f32357c43588638318e77cbf9c3",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"c42d49c7a5e64de3a202859c73c0f28e",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true}},
                      "size":{
                        "width":200,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"87cac619af3942fea52b3708ecbb6b99",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true}},
                          "size":{
                            "width":200,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"8a2ddcc5c7ab48949481b5aa4fe4d4f4",
                "label":"State3",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"91fab3f4563942d6b71144d77106f702",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":2,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true}},
                      "size":{
                        "width":170,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a19d4903a0af403d8ef1ad6dac399ed0",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":2,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true}},
                          "size":{
                            "width":170,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Buy in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"buy.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"66356ebfc5724f5e91189b6b12d1f823",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF14472},
              "location":{
                "x":780,
                "y":65},
              "size":{
                "width":110,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68c4bb59bc7d4732b03fac8b416f2ef7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF14472},
                  "location":{
                    "x":780,
                    "y":65},
                  "size":{
                    "width":110,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u40.png"}},
{
            "id":"e8b19c5fda454c9ca3cf927e460b92e6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":750,
                "y":67.5},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fcb0a10c79542e989186966f18e915e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":750,
                    "y":67.5},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u42.png"}},
{
            "id":"b4310311897e4d5ca8d970a6a1d9bca7",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":750,
                "y":98},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9a4c6c85cec046d9885a64241e3adf32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":750,
                    "y":98},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u42.png"}},
{
            "id":"e96e115872054f0eb95247f17df8cd49",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "location":{
                "x":780,
                "y":100},
              "size":{
                "width":110,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cae4721a68664050ae415a7e4bfc6a21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "location":{
                    "x":780,
                    "y":100},
                  "size":{
                    "width":110,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "554cab938fd24941ba87a0ca1d2cdc87":{
      "scriptId":"u0",
      "7a656bc70beb4cebbb674e1988d4ccb9":{
        "scriptId":"u1"},
      "c1550a7031d74549a5e3808fe28523dc":{
        "scriptId":"u2"},
      "9a64193b359b4c5687c040ea64ab310a":{
        "scriptId":"u3"},
      "5cfaf345bfe4457091303fdad238b98e":{
        "scriptId":"u4"},
      "c2fa319619ec41e39d10aee62ddb8138":{
        "scriptId":"u5"},
      "9d01a4d23d5b4b1fac75e0903a85807d":{
        "scriptId":"u6"},
      "0995ce6a56be4ebf8696cfcf5ca75c1f":{
        "scriptId":"u7"},
      "b06c0da3b5a94376a4702acc7e084e31":{
        "scriptId":"u8"},
      "58d46532d08b497c90742a6a133b2265":{
        "scriptId":"u9"},
      "65cd6803d6c74eada90e7cc5f192f6bc":{
        "scriptId":"u10"},
      "68872e9f4165442ebcb39fe8fa985046":{
        "scriptId":"u11"},
      "8d5698240ae0421e80a86a8b304f76f3":{
        "scriptId":"u12"},
      "2745e76898374f108fd8cd9b8748526f":{
        "scriptId":"u13"},
      "9e7abb7fc60344e497c13195a317e074":{
        "scriptId":"u14"},
      "9e2c0346349c476bbc513a00520db92d":{
        "scriptId":"u15"},
      "cedf53687e4e4ea191ef703b28181fd0":{
        "scriptId":"u16"},
      "1958f2ebcc884dbf835c764dd1e0632e":{
        "scriptId":"u17"},
      "28c2a1a9c2754fb5bee218a2350f544e":{
        "scriptId":"u18"},
      "095b25becc6a48e182e319ce869cfc12":{
        "scriptId":"u19"},
      "f742296fd5ba4d319cc333eefe7c3860":{
        "scriptId":"u20"},
      "5688d6e12fca40bc82107435ade74fae":{
        "scriptId":"u21"},
      "820ce519720c49cba7e04c3f8a67733a":{
        "scriptId":"u22"},
      "d52df4ad408c474184b0f50a9f5242c2":{
        "scriptId":"u23"},
      "c95cea01d0c542c38bb50a2ad316f282":{
        "scriptId":"u24"},
      "7ba4c045bc86427bb3bec19d485445a2":{
        "scriptId":"u25"},
      "df3e28c35f4b4161b72bd4f4c99b9907":{
        "scriptId":"u26"},
      "9d9b62fd3b5741d1a1de543a9481fbb4":{
        "scriptId":"u27"},
      "fbcce5ff719d4a6ca2c0ffaf89f8c834":{
        "scriptId":"u28"},
      "f317dfa0e23f4065956c33d8c541073b":{
        "scriptId":"u29"},
      "3bb420b31ba44460b717cc338975b06e":{
        "scriptId":"u30"},
      "2eaf40de2dee4350bde1920c18dcf0be":{
        "scriptId":"u31"},
      "4debd93021d842c389c5c56e4e285d99":{
        "scriptId":"u32"},
      "55317add537e442a944eab57d304f251":{
        "scriptId":"u33"},
      "07cb8e47c26449eab6398fef68b744cc":{
        "scriptId":"u34"},
      "6f2f8cacfa564d7980a579bd3e51eae0":{
        "scriptId":"u35"},
      "c42d49c7a5e64de3a202859c73c0f28e":{
        "scriptId":"u36"},
      "87cac619af3942fea52b3708ecbb6b99":{
        "scriptId":"u37"},
      "91fab3f4563942d6b71144d77106f702":{
        "scriptId":"u38"},
      "a19d4903a0af403d8ef1ad6dac399ed0":{
        "scriptId":"u39"},
      "66356ebfc5724f5e91189b6b12d1f823":{
        "scriptId":"u40"},
      "68c4bb59bc7d4732b03fac8b416f2ef7":{
        "scriptId":"u41"},
      "e8b19c5fda454c9ca3cf927e460b92e6":{
        "scriptId":"u42"},
      "6fcb0a10c79542e989186966f18e915e":{
        "scriptId":"u43"},
      "b4310311897e4d5ca8d970a6a1d9bca7":{
        "scriptId":"u44"},
      "9a4c6c85cec046d9885a64241e3adf32":{
        "scriptId":"u45"},
      "e96e115872054f0eb95247f17df8cd49":{
        "scriptId":"u46"},
      "cae4721a68664050ae415a7e4bfc6a21":{
        "scriptId":"u47"}},
    "830f6a44e5894f19be6af482e54ff6b7":{
      "scriptId":"u48"},
    "ce4d32935337479291854abc5b8aa7f7":{
      "scriptId":"u49"},
    "df42d89f9b7d401f95dfe734bbed2399":{
      "scriptId":"u50"},
    "2306fbc5269f40fd9faadfc887d0953c":{
      "scriptId":"u51"},
    "4c4fb594aba346cd8375e6ab9de6f714":{
      "scriptId":"u52"},
    "fc3f10c79c874be4a844547d59cfac53":{
      "scriptId":"u53"},
    "e3f87361095d400b9a846c87380ca7c3":{
      "scriptId":"u54"},
    "22520588882344f48f9b0ecb28101f5c":{
      "scriptId":"u55"},
    "4b1406026a6d42848108380a5f62f026":{
      "scriptId":"u56"},
    "7521008274ae4d6a9ef15e7ca6b2cc02":{
      "scriptId":"u57"},
    "cf646c9879ec423eadafb91ed80b40fe":{
      "scriptId":"u58"},
    "d20086156775402a9a8311ad616edaf6":{
      "scriptId":"u59"},
    "99d7dde72986415187170ac9cedbb0c3":{
      "scriptId":"u60"},
    "dd49dddc6a4c475cb4d00edfa2b53a6f":{
      "scriptId":"u61"},
    "19a4041cd6394f9693e09401e233ec24":{
      "scriptId":"u62"},
    "4387524a14df4cb3b157f3e00a42d8d6":{
      "scriptId":"u63"},
    "2237c3c92f9a477e88aa5209f3824c8b":{
      "scriptId":"u64"},
    "f861455366da47218efb5ab2d8730e97":{
      "scriptId":"u65"},
    "9d00821ab14f41c187c26ebd0227c950":{
      "scriptId":"u66"},
    "61a8e7ff202342ffaf5dca5c9ebfd2d4":{
      "scriptId":"u67"},
    "7fd7c6773eb54599a0ab93d04032f492":{
      "scriptId":"u68"},
    "2d231036358a4f419544eebea5f6fc99":{
      "scriptId":"u69"},
    "396f66f7f2e44f6c9446cfecf92dbae5":{
      "scriptId":"u70"},
    "66e5f463706a48019900682f2d8234b0":{
      "scriptId":"u71"},
    "63c2de10cb554d9b91e9552e8c18e764":{
      "scriptId":"u72"},
    "b73086be9cd6487684b400619ab5c2e8":{
      "scriptId":"u73"},
    "dc07e30f8c6b4e2a88f345cb3971f5ac":{
      "scriptId":"u74"},
    "0c31a9690bb94f04bbf1dbc11627c007":{
      "scriptId":"u75"},
    "ef9abde5354a43b4a040215710a92bac":{
      "scriptId":"u76"},
    "b9acdda4f3734be4a610b249b1086a6e":{
      "scriptId":"u77"},
    "0f328a3870af4848ab4dc8f103fed504":{
      "scriptId":"u78"},
    "abc4b8054f8043cfad35576fc487be16":{
      "scriptId":"u79"},
    "96e8fde9109b4e19984f6e043eeef63a":{
      "scriptId":"u80"},
    "8eb0bdf964a3460e991f3ae385b3c333":{
      "scriptId":"u81"},
    "a35d1986f83544888a6c76f8eecc96a3":{
      "scriptId":"u82"},
    "f9b6461be08e44168ee550a1d8a8cdab":{
      "scriptId":"u83"},
    "ed1bc104055c45b8afd76ca3169e21ce":{
      "scriptId":"u84"},
    "eb1302739c194ee5a75f5ad88e99704c":{
      "scriptId":"u85"},
    "4b951842481f45f98fb14b310135f60a":{
      "scriptId":"u86"},
    "238665adb09740caabd277f3cd2b48da":{
      "scriptId":"u87"},
    "51903c2138594e239ca2b98fb89204f4":{
      "scriptId":"u88"},
    "6a6bfb0020c24c6f95f1396746a72679":{
      "scriptId":"u89"},
    "4d825f195d654142a401a2d673e11c6d":{
      "scriptId":"u90"},
    "e8674b82a8c54261a33f3cee3f032262":{
      "scriptId":"u91"},
    "321f4f324433488c8a325113d629116d":{
      "scriptId":"u92"},
    "28227a5d87df4ea181908f395b0e3acf":{
      "scriptId":"u93"}}});