$axure.loadCurrentPage({
  "url":"order.html",
  "generationDate":new Date(1409910099893.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a6adb75f36934e95b5f3280cf435971d",
    "type":"Axure:Page",
    "name":"order",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"43",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setPanelState",
                "description":"Set Header/bucket to State2 fade out 500ms fade in 500ms",
                "panelsToStates":[{
                    "panelPath":["554cab938fd24941ba87a0ca1d2cdc87",
"55317add537e442a944eab57d304f251"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":2,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":false,
                      "options":{
                        "animateOut":{
                          "easing":"fade",
                          "duration":500},
                        "animateIn":{
                          "easing":"fade",
                          "duration":500},
                        "compress":false}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"554cab938fd24941ba87a0ca1d2cdc87",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fdae7ed1a7a54530b5f4cecce3fbfa3f"},
{
          "id":"830f6a44e5894f19be6af482e54ff6b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":301,
              "y":420},
            "size":{
              "width":266,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce4d32935337479291854abc5b8aa7f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":301,
                  "y":420},
                "size":{
                  "width":266,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df42d89f9b7d401f95dfe734bbed2399",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":90,
              "y":425},
            "size":{
              "width":184,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2306fbc5269f40fd9faadfc887d0953c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF91ABC8,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":425},
                "size":{
                  "width":184,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c4fb594aba346cd8375e6ab9de6f714",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":428},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u54_line.png"}},
{
          "id":"83d48472711044f0b459debaed55bbaa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":90,
              "y":480},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/order/u53_image_sketch.png",
            "disabled~":"images/order/u53_disabled.png"}},
{
          "id":"4c0ad707bf8e486c8e73185ef059f486",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":90,
              "y":530},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/order/u53_image_sketch.png",
            "disabled~":"images/order/u53_disabled.png"}},
{
          "id":"11e918baecf340e8b7c8f961b22c3a69",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":90,
              "y":580},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/order/u53_image_sketch.png",
            "disabled~":"images/order/u53_disabled.png"}},
{
          "id":"b37abe3dedd644e4b24b61a22044cd36",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":600,
              "y":480},
            "size":{
              "width":290,
              "height":125}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/order/u56_image_sketch.png",
            "disabled~":"images/order/u56_disabled.png"}},
{
          "id":"438206a879c14fb0bd3e878e165069e8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":630},
            "size":{
              "width":800,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/order/u57_line.png"}},
{
          "id":"fbfd5e6f987644389df9ae31eb48fb35",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":416,
              "y":658},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open order-accepted in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"order-accepted.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/order/u58_image_sketch.png",
            "disabled~":"images/order/u58_disabled.png"}},
{
          "id":"53a0bbe81ad34ba4bcb0db0b20f9494f",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":300,
              "y":480},
            "size":{
              "width":280,
              "height":125}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/order/u59_image_sketch.png",
            "disabled~":"images/order/u59_disabled.png"}},
{
          "id":"270683edb00e46e887514b1b6de00127",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":720}},
          "adaptiveStyles":{
},
          "masterId":"8ab8a1c37a8e4d5e9b96f442de065e8f"}]}},
  "masters":{
    "fdae7ed1a7a54530b5f4cecce3fbfa3f":{
      "packageId":"fdae7ed1a7a54530b5f4cecce3fbfa3f",
      "type":"Axure:Master",
      "name":"Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7a656bc70beb4cebbb674e1988d4ccb9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":650,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1550a7031d74549a5e3808fe28523dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":650,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"9a64193b359b4c5687c040ea64ab310a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":410,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5cfaf345bfe4457091303fdad238b98e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":410,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"c2fa319619ec41e39d10aee62ddb8138",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9d01a4d23d5b4b1fac75e0903a85807d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Catalog in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"catalog.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"0995ce6a56be4ebf8696cfcf5ca75c1f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD9E2EC},
              "location":{
                "x":70,
                "y":320},
              "size":{
                "width":820,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b06c0da3b5a94376a4702acc7e084e31",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD9E2EC},
                  "location":{
                    "x":70,
                    "y":320},
                  "size":{
                    "width":820,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u7.png"}},
{
            "id":"58d46532d08b497c90742a6a133b2265",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":150,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"65cd6803d6c74eada90e7cc5f192f6bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":150,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Catalog in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"catalog.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/buy/u9.png"}},
{
            "id":"68872e9f4165442ebcb39fe8fa985046",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":390,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d5698240ae0421e80a86a8b304f76f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":390,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u9.png"}},
{
            "id":"2745e76898374f108fd8cd9b8748526f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":630,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9e7abb7fc60344e497c13195a317e074",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":630,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u9.png"}},
{
            "id":"9e2c0346349c476bbc513a00520db92d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":342},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cedf53687e4e4ea191ef703b28181fd0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":342},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u15.png"}},
{
            "id":"1958f2ebcc884dbf835c764dd1e0632e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF14472,
                "opacity":1},
              "location":{
                "x":410,
                "y":14},
              "size":{
                "width":140,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"28c2a1a9c2754fb5bee218a2350f544e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF14472,
                    "opacity":1},
                  "location":{
                    "x":410,
                    "y":14},
                  "size":{
                    "width":140,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Elefan in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"elefan.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"095b25becc6a48e182e319ce869cfc12",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":394.5,
                "y":110},
              "size":{
                "width":171,
                "height":25}},
            "adaptiveStyles":{
},
            "images":{
              "normal~":"images/buy/u19_image_sketch.png",
              "disabled~":"images/buy/u19_disabled.png"}},
{
            "id":"f742296fd5ba4d319cc333eefe7c3860",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":110},
              "size":{
                "width":25,
                "height":25}},
            "adaptiveStyles":{
},
            "images":{
              "normal~":"images/elefan/u20_image_sketch.png",
              "disabled~":"images/elefan/u20_disabled.png"}},
{
            "id":"5688d6e12fca40bc82107435ade74fae",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":324,
                "y":70},
              "size":{
                "width":82,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"820ce519720c49cba7e04c3f8a67733a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":324,
                    "y":70},
                  "size":{
                    "width":82,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d52df4ad408c474184b0f50a9f5242c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":424,
                "y":70},
              "size":{
                "width":132,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c95cea01d0c542c38bb50a2ad316f282",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":424,
                    "y":70},
                  "size":{
                    "width":132,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Payment in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"payment.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7ba4c045bc86427bb3bec19d485445a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":566,
                "y":70},
              "size":{
                "width":70,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df3e28c35f4b4161b72bd4f4c99b9907",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":566,
                    "y":70},
                  "size":{
                    "width":70,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9d9b62fd3b5741d1a1de543a9481fbb4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":660,
                "y":26},
              "size":{
                "width":230,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fbcce5ff719d4a6ca2c0ffaf89f8c834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":660,
                    "y":26},
                  "size":{
                    "width":230,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f317dfa0e23f4065956c33d8c541073b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":28},
              "size":{
                "width":32,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3bb420b31ba44460b717cc338975b06e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":28},
                  "size":{
                    "width":32,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u29.png"}},
{
            "id":"2eaf40de2dee4350bde1920c18dcf0be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":132,
                "y":26},
              "size":{
                "width":148,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4debd93021d842c389c5c56e4e285d99",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":132,
                    "y":26},
                  "size":{
                    "width":148,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"55317add537e442a944eab57d304f251",
            "label":"bucket",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":132,
                "y":45},
              "size":{
                "width":148,
                "height":22}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Buy in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"buy.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"618cad80e4c7413b886dfb19397c0e88",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"07cb8e47c26449eab6398fef68b744cc",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "size":{
                        "width":148,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6f2f8cacfa564d7980a579bd3e51eae0",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "size":{
                            "width":148,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"ec420f32357c43588638318e77cbf9c3",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"c42d49c7a5e64de3a202859c73c0f28e",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true}},
                      "size":{
                        "width":200,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"87cac619af3942fea52b3708ecbb6b99",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true}},
                          "size":{
                            "width":200,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"8a2ddcc5c7ab48949481b5aa4fe4d4f4",
                "label":"State3",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"91fab3f4563942d6b71144d77106f702",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":2,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true}},
                      "size":{
                        "width":170,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a19d4903a0af403d8ef1ad6dac399ed0",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":2,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true}},
                          "size":{
                            "width":170,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Buy in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"buy.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"66356ebfc5724f5e91189b6b12d1f823",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF14472},
              "location":{
                "x":780,
                "y":65},
              "size":{
                "width":110,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68c4bb59bc7d4732b03fac8b416f2ef7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF14472},
                  "location":{
                    "x":780,
                    "y":65},
                  "size":{
                    "width":110,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u40.png"}},
{
            "id":"e8b19c5fda454c9ca3cf927e460b92e6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":750,
                "y":67.5},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fcb0a10c79542e989186966f18e915e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":750,
                    "y":67.5},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u42.png"}},
{
            "id":"b4310311897e4d5ca8d970a6a1d9bca7",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":750,
                "y":98},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9a4c6c85cec046d9885a64241e3adf32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":750,
                    "y":98},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u42.png"}},
{
            "id":"e96e115872054f0eb95247f17df8cd49",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "location":{
                "x":780,
                "y":100},
              "size":{
                "width":110,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cae4721a68664050ae415a7e4bfc6a21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "location":{
                    "x":780,
                    "y":100},
                  "size":{
                    "width":110,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "8ab8a1c37a8e4d5e9b96f442de065e8f":{
      "packageId":"8ab8a1c37a8e4d5e9b96f442de065e8f",
      "type":"Axure:Master",
      "name":"inner_footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"526cf45a44c24a78b3cb835ab858a30d",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":72,
                "y":1580},
              "size":{
                "width":818,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/buy/u58_line.png"}},
{
            "id":"336bef24b54d4992a996775c18dd1693",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Oblique', 'Tahoma'",
              "fontStyle":"oblique",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0080,
                "opacity":1},
              "location":{
                "x":72,
                "y":1554},
              "size":{
                "width":68,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1a4bb54c0c594ae6af265fdcc2edf35b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Oblique', 'Tahoma'",
                  "fontStyle":"oblique",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0080,
                    "opacity":1},
                  "location":{
                    "x":72,
                    "y":1554},
                  "size":{
                    "width":68,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"71eca94b03f444f4b1e0f7d64b731654",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Oblique', 'Tahoma'",
              "fontStyle":"oblique",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0080,
                "opacity":1},
              "location":{
                "x":160,
                "y":1554},
              "size":{
                "width":112,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"632f38e526844766a97ea81389781e35",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Oblique', 'Tahoma'",
                  "fontStyle":"oblique",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0080,
                    "opacity":1},
                  "location":{
                    "x":160,
                    "y":1554},
                  "size":{
                    "width":112,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Payment in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"payment.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"593dec9c236c4bccb6d2c9f988cea6f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Oblique', 'Tahoma'",
              "fontStyle":"oblique",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0080,
                "opacity":1},
              "location":{
                "x":290,
                "y":1554},
              "size":{
                "width":56,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a9f6be9c1a6046c78072d6d912f99912",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Oblique', 'Tahoma'",
                  "fontStyle":"oblique",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0080,
                    "opacity":1},
                  "location":{
                    "x":290,
                    "y":1554},
                  "size":{
                    "width":56,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6a442e289d4547e79bac07f36cc99590",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":660,
                "y":1554},
              "size":{
                "width":230,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c2dec196fb01426a85f70212efc25756",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":660,
                    "y":1554},
                  "size":{
                    "width":230,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2b4e976131564c8eb09815268860ffcd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "location":{
                "x":72,
                "y":1600},
              "size":{
                "width":296,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53af5fe5a5de4d74be6b0e18b026fb1b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "location":{
                    "x":72,
                    "y":1600},
                  "size":{
                    "width":296,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4443304dd6c244e6b4024f739f15be00",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"right",
              "location":{
                "x":660,
                "y":1600},
              "size":{
                "width":230,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4fa3189fbc1448c1ba9ec315101db934",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"right",
                  "location":{
                    "x":660,
                    "y":1600},
                  "size":{
                    "width":230,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7bccd5c1de934b79be5cdaf5d738e113",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":474,
                "y":1554},
              "size":{
                "width":46,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c09c8d964c434e05a40820eb0ee68be1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":474,
                    "y":1554},
                  "size":{
                    "width":46,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"93d2f4612341437494f40624c16d4d49",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":90,
                "y":1440},
              "size":{
                "width":134,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f8d8b71ec6584d06a4b2973a7e541ace",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":90,
                    "y":1440},
                  "size":{
                    "width":134,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9878a03e0a77464fb5b065fe46a860a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"09d80c8906e44ea4938bef6756d98914",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"a9fc783f7579426aabd34075a3a6b9c1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"36f1a4497f5c4d51a0c9cf1c3c42d63a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"75ae363121444236b80170f5b07a5862",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f0ce727b4594b70adc42ee719af4371",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"303d0363da7241f69c32acc5d419d7bd",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":240,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"654624eb5b10426091fcb958865f7074",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":240,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"622ed9762b194e5ea18a46c31ae32b75",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":734,
                "y":1440},
              "size":{
                "width":140,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2a9fbad65bd64d2cbe7cb759fdd3a0c8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":734,
                    "y":1440},
                  "size":{
                    "width":140,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1c03beb352344481b64e5d95e20e349f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":734,
                "y":1480},
              "size":{
                "width":21,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2da5e5b8cbc747e590062c13a6882585",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":734,
                    "y":1480},
                  "size":{
                    "width":21,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u234.png"}},
{
            "id":"8f63b256b27b49b8b63910d4bb4b1d81",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":764,
                "y":1480},
              "size":{
                "width":21,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d9ded5b8bdd8429ca26b9bf9faec9c0f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":764,
                    "y":1480},
                  "size":{
                    "width":21,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u234.png"}},
{
            "id":"596458da3f89451e8bada7901a108411",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":793,
                "y":1480},
              "size":{
                "width":21,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d1e395b3107c4fa5affa69e3b986c566",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":793,
                    "y":1480},
                  "size":{
                    "width":21,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u234.png"}},
{
            "id":"7c711f358a3f40baa34adfd8542b0541",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":823,
                "y":1480},
              "size":{
                "width":21,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fc0b9946d49c49e78da8ecd2ef8f3b81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":823,
                    "y":1480},
                  "size":{
                    "width":21,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u234.png"}},
{
            "id":"027397ed768d4c259881c97c86ecd3f4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":853,
                "y":1480},
              "size":{
                "width":21,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2c444a8082864736be4a09bc3f73097f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":853,
                    "y":1480},
                  "size":{
                    "width":21,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u234.png"}},
{
            "id":"c75f6497ffd04d9faad296a0e7b181a4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":290,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8145a1a8bbe744c3bf0ff091948068d8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":290,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"321383f8272e463b8d4bb4b4a3a3daf4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":340,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f3d212db8ec407da5aa4d51bd9217fe",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":340,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"50b2f2c41fd445b28a88b59971247322",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":390,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e60e4e347b5e499aa31547cb8566feb5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":390,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"3e70c9a29891493ea2634b6232ed4274",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":440,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d61b63cf6c034dfeb32e78483a3fbe7e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":440,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"287d4218706345daaf8c70efe94a8c5b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":490,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"48e65774f089457bba31386e5e56296b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":490,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"d50a5b602a1a4fcb8f50e3b1795e2cad",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d291668f65bf4f1e8593a1d35b6b830c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":540,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"b029d6432ef643389e6b45010121e2a5",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":590,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"07cd91acb4a7409da22110ce9c4150ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":590,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"d213cb866ea842508d805fd1c2b95471",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":640,
                "y":1470},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"31efba9d66bf42ecb58c09fc9824ee2d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":640,
                    "y":1470},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u220.png"}},
{
            "id":"20ebf5b1a4084eaeae2d16b72ccb8692",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Oblique', 'Tahoma'",
              "fontStyle":"oblique",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0080,
                "opacity":1},
              "location":{
                "x":364,
                "y":1554},
              "size":{
                "width":83,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9fde456b51b04576b8f526efc0be6fac",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Oblique', 'Tahoma'",
                  "fontStyle":"oblique",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0080,
                    "opacity":1},
                  "location":{
                    "x":364,
                    "y":1554},
                  "size":{
                    "width":83,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "554cab938fd24941ba87a0ca1d2cdc87":{
      "scriptId":"u0",
      "7a656bc70beb4cebbb674e1988d4ccb9":{
        "scriptId":"u1"},
      "c1550a7031d74549a5e3808fe28523dc":{
        "scriptId":"u2"},
      "9a64193b359b4c5687c040ea64ab310a":{
        "scriptId":"u3"},
      "5cfaf345bfe4457091303fdad238b98e":{
        "scriptId":"u4"},
      "c2fa319619ec41e39d10aee62ddb8138":{
        "scriptId":"u5"},
      "9d01a4d23d5b4b1fac75e0903a85807d":{
        "scriptId":"u6"},
      "0995ce6a56be4ebf8696cfcf5ca75c1f":{
        "scriptId":"u7"},
      "b06c0da3b5a94376a4702acc7e084e31":{
        "scriptId":"u8"},
      "58d46532d08b497c90742a6a133b2265":{
        "scriptId":"u9"},
      "65cd6803d6c74eada90e7cc5f192f6bc":{
        "scriptId":"u10"},
      "68872e9f4165442ebcb39fe8fa985046":{
        "scriptId":"u11"},
      "8d5698240ae0421e80a86a8b304f76f3":{
        "scriptId":"u12"},
      "2745e76898374f108fd8cd9b8748526f":{
        "scriptId":"u13"},
      "9e7abb7fc60344e497c13195a317e074":{
        "scriptId":"u14"},
      "9e2c0346349c476bbc513a00520db92d":{
        "scriptId":"u15"},
      "cedf53687e4e4ea191ef703b28181fd0":{
        "scriptId":"u16"},
      "1958f2ebcc884dbf835c764dd1e0632e":{
        "scriptId":"u17"},
      "28c2a1a9c2754fb5bee218a2350f544e":{
        "scriptId":"u18"},
      "095b25becc6a48e182e319ce869cfc12":{
        "scriptId":"u19"},
      "f742296fd5ba4d319cc333eefe7c3860":{
        "scriptId":"u20"},
      "5688d6e12fca40bc82107435ade74fae":{
        "scriptId":"u21"},
      "820ce519720c49cba7e04c3f8a67733a":{
        "scriptId":"u22"},
      "d52df4ad408c474184b0f50a9f5242c2":{
        "scriptId":"u23"},
      "c95cea01d0c542c38bb50a2ad316f282":{
        "scriptId":"u24"},
      "7ba4c045bc86427bb3bec19d485445a2":{
        "scriptId":"u25"},
      "df3e28c35f4b4161b72bd4f4c99b9907":{
        "scriptId":"u26"},
      "9d9b62fd3b5741d1a1de543a9481fbb4":{
        "scriptId":"u27"},
      "fbcce5ff719d4a6ca2c0ffaf89f8c834":{
        "scriptId":"u28"},
      "f317dfa0e23f4065956c33d8c541073b":{
        "scriptId":"u29"},
      "3bb420b31ba44460b717cc338975b06e":{
        "scriptId":"u30"},
      "2eaf40de2dee4350bde1920c18dcf0be":{
        "scriptId":"u31"},
      "4debd93021d842c389c5c56e4e285d99":{
        "scriptId":"u32"},
      "55317add537e442a944eab57d304f251":{
        "scriptId":"u33"},
      "07cb8e47c26449eab6398fef68b744cc":{
        "scriptId":"u34"},
      "6f2f8cacfa564d7980a579bd3e51eae0":{
        "scriptId":"u35"},
      "c42d49c7a5e64de3a202859c73c0f28e":{
        "scriptId":"u36"},
      "87cac619af3942fea52b3708ecbb6b99":{
        "scriptId":"u37"},
      "91fab3f4563942d6b71144d77106f702":{
        "scriptId":"u38"},
      "a19d4903a0af403d8ef1ad6dac399ed0":{
        "scriptId":"u39"},
      "66356ebfc5724f5e91189b6b12d1f823":{
        "scriptId":"u40"},
      "68c4bb59bc7d4732b03fac8b416f2ef7":{
        "scriptId":"u41"},
      "e8b19c5fda454c9ca3cf927e460b92e6":{
        "scriptId":"u42"},
      "6fcb0a10c79542e989186966f18e915e":{
        "scriptId":"u43"},
      "b4310311897e4d5ca8d970a6a1d9bca7":{
        "scriptId":"u44"},
      "9a4c6c85cec046d9885a64241e3adf32":{
        "scriptId":"u45"},
      "e96e115872054f0eb95247f17df8cd49":{
        "scriptId":"u46"},
      "cae4721a68664050ae415a7e4bfc6a21":{
        "scriptId":"u47"}},
    "830f6a44e5894f19be6af482e54ff6b7":{
      "scriptId":"u48"},
    "ce4d32935337479291854abc5b8aa7f7":{
      "scriptId":"u49"},
    "df42d89f9b7d401f95dfe734bbed2399":{
      "scriptId":"u50"},
    "2306fbc5269f40fd9faadfc887d0953c":{
      "scriptId":"u51"},
    "4c4fb594aba346cd8375e6ab9de6f714":{
      "scriptId":"u52"},
    "83d48472711044f0b459debaed55bbaa":{
      "scriptId":"u53"},
    "4c0ad707bf8e486c8e73185ef059f486":{
      "scriptId":"u54"},
    "11e918baecf340e8b7c8f961b22c3a69":{
      "scriptId":"u55"},
    "b37abe3dedd644e4b24b61a22044cd36":{
      "scriptId":"u56"},
    "438206a879c14fb0bd3e878e165069e8":{
      "scriptId":"u57"},
    "fbfd5e6f987644389df9ae31eb48fb35":{
      "scriptId":"u58"},
    "53a0bbe81ad34ba4bcb0db0b20f9494f":{
      "scriptId":"u59"},
    "270683edb00e46e887514b1b6de00127":{
      "scriptId":"u60",
      "526cf45a44c24a78b3cb835ab858a30d":{
        "scriptId":"u61"},
      "336bef24b54d4992a996775c18dd1693":{
        "scriptId":"u62"},
      "1a4bb54c0c594ae6af265fdcc2edf35b":{
        "scriptId":"u63"},
      "71eca94b03f444f4b1e0f7d64b731654":{
        "scriptId":"u64"},
      "632f38e526844766a97ea81389781e35":{
        "scriptId":"u65"},
      "593dec9c236c4bccb6d2c9f988cea6f2":{
        "scriptId":"u66"},
      "a9f6be9c1a6046c78072d6d912f99912":{
        "scriptId":"u67"},
      "6a442e289d4547e79bac07f36cc99590":{
        "scriptId":"u68"},
      "c2dec196fb01426a85f70212efc25756":{
        "scriptId":"u69"},
      "2b4e976131564c8eb09815268860ffcd":{
        "scriptId":"u70"},
      "53af5fe5a5de4d74be6b0e18b026fb1b":{
        "scriptId":"u71"},
      "4443304dd6c244e6b4024f739f15be00":{
        "scriptId":"u72"},
      "4fa3189fbc1448c1ba9ec315101db934":{
        "scriptId":"u73"},
      "7bccd5c1de934b79be5cdaf5d738e113":{
        "scriptId":"u74"},
      "c09c8d964c434e05a40820eb0ee68be1":{
        "scriptId":"u75"},
      "93d2f4612341437494f40624c16d4d49":{
        "scriptId":"u76"},
      "f8d8b71ec6584d06a4b2973a7e541ace":{
        "scriptId":"u77"},
      "9878a03e0a77464fb5b065fe46a860a6":{
        "scriptId":"u78"},
      "09d80c8906e44ea4938bef6756d98914":{
        "scriptId":"u79"},
      "a9fc783f7579426aabd34075a3a6b9c1":{
        "scriptId":"u80"},
      "36f1a4497f5c4d51a0c9cf1c3c42d63a":{
        "scriptId":"u81"},
      "75ae363121444236b80170f5b07a5862":{
        "scriptId":"u82"},
      "8f0ce727b4594b70adc42ee719af4371":{
        "scriptId":"u83"},
      "303d0363da7241f69c32acc5d419d7bd":{
        "scriptId":"u84"},
      "654624eb5b10426091fcb958865f7074":{
        "scriptId":"u85"},
      "622ed9762b194e5ea18a46c31ae32b75":{
        "scriptId":"u86"},
      "2a9fbad65bd64d2cbe7cb759fdd3a0c8":{
        "scriptId":"u87"},
      "1c03beb352344481b64e5d95e20e349f":{
        "scriptId":"u88"},
      "2da5e5b8cbc747e590062c13a6882585":{
        "scriptId":"u89"},
      "8f63b256b27b49b8b63910d4bb4b1d81":{
        "scriptId":"u90"},
      "d9ded5b8bdd8429ca26b9bf9faec9c0f":{
        "scriptId":"u91"},
      "596458da3f89451e8bada7901a108411":{
        "scriptId":"u92"},
      "d1e395b3107c4fa5affa69e3b986c566":{
        "scriptId":"u93"},
      "7c711f358a3f40baa34adfd8542b0541":{
        "scriptId":"u94"},
      "fc0b9946d49c49e78da8ecd2ef8f3b81":{
        "scriptId":"u95"},
      "027397ed768d4c259881c97c86ecd3f4":{
        "scriptId":"u96"},
      "2c444a8082864736be4a09bc3f73097f":{
        "scriptId":"u97"},
      "c75f6497ffd04d9faad296a0e7b181a4":{
        "scriptId":"u98"},
      "8145a1a8bbe744c3bf0ff091948068d8":{
        "scriptId":"u99"},
      "321383f8272e463b8d4bb4b4a3a3daf4":{
        "scriptId":"u100"},
      "8f3d212db8ec407da5aa4d51bd9217fe":{
        "scriptId":"u101"},
      "50b2f2c41fd445b28a88b59971247322":{
        "scriptId":"u102"},
      "e60e4e347b5e499aa31547cb8566feb5":{
        "scriptId":"u103"},
      "3e70c9a29891493ea2634b6232ed4274":{
        "scriptId":"u104"},
      "d61b63cf6c034dfeb32e78483a3fbe7e":{
        "scriptId":"u105"},
      "287d4218706345daaf8c70efe94a8c5b":{
        "scriptId":"u106"},
      "48e65774f089457bba31386e5e56296b":{
        "scriptId":"u107"},
      "d50a5b602a1a4fcb8f50e3b1795e2cad":{
        "scriptId":"u108"},
      "d291668f65bf4f1e8593a1d35b6b830c":{
        "scriptId":"u109"},
      "b029d6432ef643389e6b45010121e2a5":{
        "scriptId":"u110"},
      "07cd91acb4a7409da22110ce9c4150ed":{
        "scriptId":"u111"},
      "d213cb866ea842508d805fd1c2b95471":{
        "scriptId":"u112"},
      "31efba9d66bf42ecb58c09fc9824ee2d":{
        "scriptId":"u113"},
      "20ebf5b1a4084eaeae2d16b72ccb8692":{
        "scriptId":"u114"},
      "9fde456b51b04576b8f526efc0be6fac":{
        "scriptId":"u115"}}}});