$axure.loadCurrentPage({
  "url":"order.html",
  "generationDate":new Date(1409664629141.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a6adb75f36934e95b5f3280cf435971d",
    "type":"Axure:Page",
    "name":"order",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"43",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setPanelState",
                "description":"Set Header/bucket to State2 fade out 500ms fade in 500ms",
                "panelsToStates":[{
                    "panelPath":["554cab938fd24941ba87a0ca1d2cdc87",
"55317add537e442a944eab57d304f251"],
                    "stateInfo":{
                      "setStateType":"diagram",
                      "stateNumber":2,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":false,
                      "showWhenSet":false,
                      "options":{
                        "animateOut":{
                          "easing":"fade",
                          "duration":500},
                        "animateIn":{
                          "easing":"fade",
                          "duration":500},
                        "compress":false}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"554cab938fd24941ba87a0ca1d2cdc87",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fdae7ed1a7a54530b5f4cecce3fbfa3f"},
{
          "id":"830f6a44e5894f19be6af482e54ff6b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":301,
              "y":420},
            "size":{
              "width":266,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce4d32935337479291854abc5b8aa7f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":301,
                  "y":420},
                "size":{
                  "width":266,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df42d89f9b7d401f95dfe734bbed2399",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":90,
              "y":425},
            "size":{
              "width":184,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2306fbc5269f40fd9faadfc887d0953c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF91ABC8,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":425},
                "size":{
                  "width":184,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c4fb594aba346cd8375e6ab9de6f714",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":428},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u96_line.png"}},
{
          "id":"83d48472711044f0b459debaed55bbaa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":90,
              "y":480},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/buy/u78_image_sketch.png",
            "disabled~":"images/buy/u78_disabled.png"}},
{
          "id":"4c0ad707bf8e486c8e73185ef059f486",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":90,
              "y":530},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/buy/u78_image_sketch.png",
            "disabled~":"images/buy/u78_disabled.png"}},
{
          "id":"11e918baecf340e8b7c8f961b22c3a69",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":90,
              "y":580},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/buy/u78_image_sketch.png",
            "disabled~":"images/buy/u78_disabled.png"}},
{
          "id":"97973b67f8ae45e0aa379c7e6ce744a0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":310,
              "y":530},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/buy/u78_image_sketch.png",
            "disabled~":"images/buy/u78_disabled.png"}},
{
          "id":"88b41f6ab1ef45c29ce66f66d57b5be3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":310,
              "y":480},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/buy/u78_image_sketch.png",
            "disabled~":"images/buy/u78_disabled.png"}},
{
          "id":"abd46bd4b4234c0dbeba39a927d4ba82",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":310,
              "y":580},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/buy/u78_image_sketch.png",
            "disabled~":"images/buy/u78_disabled.png"}},
{
          "id":"b37abe3dedd644e4b24b61a22044cd36",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":530,
              "y":480},
            "size":{
              "width":360,
              "height":125}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/order/u59_image_sketch.png",
            "disabled~":"images/order/u59_disabled.png"}},
{
          "id":"438206a879c14fb0bd3e878e165069e8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":630},
            "size":{
              "width":800,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/order/u60_line.png"}},
{
          "id":"fbfd5e6f987644389df9ae31eb48fb35",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":416,
              "y":658},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open order-accepted in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"order-accepted.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/order/u61_image_sketch.png",
            "disabled~":"images/order/u61_disabled.png"}},
{
          "id":"134b45c1c09f4c90ac4ffa307f1ea6a7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":880},
            "size":{
              "width":818,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/buy/u49_line.png"}},
{
          "id":"15916a1ceaf748219816ffa217735e7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Oblique', 'Tahoma'",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":72,
              "y":854},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3e46b24841c406aae6303b1a5638bea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Oblique', 'Tahoma'",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":72,
                  "y":854},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open About in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"about.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"551a5037a215461b84cf13522596d046",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Oblique', 'Tahoma'",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":160,
              "y":854},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53acb3668fe0491692c20a6b316b51d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Oblique', 'Tahoma'",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":160,
                  "y":854},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Payment in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"payment.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"951ac30ef3944cee9efc860d4d4b4d9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Oblique', 'Tahoma'",
            "fontStyle":"oblique",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":290,
              "y":854},
            "size":{
              "width":56,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4934be60ccb54fe4a6ef7addbe3f7af2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Oblique', 'Tahoma'",
                "fontStyle":"oblique",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":854},
                "size":{
                  "width":56,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Contacts in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"contacts.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"619d8227db5541cab8593a2a86f6e609",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF768FA8,
              "opacity":1},
            "location":{
              "x":660,
              "y":854},
            "size":{
              "width":230,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aeb82b87c2447fea6ea550d6e30e16e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF768FA8,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":854},
                "size":{
                  "width":230,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acc1d7ad13654721bb90251a286f1fb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "location":{
              "x":72,
              "y":900},
            "size":{
              "width":296,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2aa687fe62f44029c477e0a93ff29ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "location":{
                  "x":72,
                  "y":900},
                "size":{
                  "width":296,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd1ac9fdc3f04caa939a60dd418f0381",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "horizontalAlignment":"right",
            "location":{
              "x":660,
              "y":900},
            "size":{
              "width":230,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72c6fda1fd10497cbe45d652097bfc22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "horizontalAlignment":"right",
                "location":{
                  "x":660,
                  "y":900},
                "size":{
                  "width":230,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5ef40601bb14748abe120e8f8bfea91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF768FA8,
              "opacity":1},
            "location":{
              "x":90,
              "y":740},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62e639c783a44b51b13f8238c89b14ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF768FA8,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":740},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39abc06b618a453bafc536d404e4a7fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":770},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa461fa04da34dcb976f85881811ddd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":770},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u211.png"}},
{
          "id":"996158340d3545f1adf2b098c58039b9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":770},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12ae9bbe502e4583bd36dbdf998292eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":770},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u211.png"}},
{
          "id":"0999a9da0ba5432b9faa70972d819f0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":770},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41d2b7aa4ba44a0ca1753aae92f8836c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":770},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u211.png"}},
{
          "id":"b65f7a1fca564044be443141f6962412",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":770},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e32444706b64f0fbe35f260f12cc8cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":770},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u211.png"}},
{
          "id":"9893e2c07fcd4d52a67afb66fac455bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":384,
              "y":740},
            "size":{
              "width":210,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8b211fbec2c4aaba7ba76744b02ea34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":384,
                  "y":740},
                "size":{
                  "width":210,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46a92597f4fd44afaa7ca23fb078dbdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF768FA8,
              "opacity":1},
            "location":{
              "x":734,
              "y":740},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a03984d5bc345189096a9307fc6286b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF768FA8,
                  "opacity":1},
                "location":{
                  "x":734,
                  "y":740},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c8f4fc97c174e99b8c691554d6eec64",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":389,
              "y":778},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/buy/u78_image_sketch.png",
            "disabled~":"images/buy/u78_disabled.png"}},
{
          "id":"5c1e56abf6ad42c6b3fdd6c0097ccdad",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":566,
              "y":778},
            "size":{
              "width":28,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/elefan/u224_image_sketch.png",
            "disabled~":"images/elefan/u224_disabled.png"}},
{
          "id":"c05a08ccfc65405d984e243ef954a7e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":734,
              "y":780},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7639c4f6ad19466a911ca4fc12f2c01a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":734,
                  "y":780},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u225.png"}},
{
          "id":"3c81fdaa3b7d4156b9b4163e09966db8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":764,
              "y":780},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3c4b55cdfc3494380980956c19b4c8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":764,
                  "y":780},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u225.png"}},
{
          "id":"8509e83b853d4e43a6055cc57898b137",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":793,
              "y":780},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21cbb0f837fe402faa95f77a072be264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":793,
                  "y":780},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u225.png"}},
{
          "id":"91147b39515742778c7538a48d8bf1a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":823,
              "y":780},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7610835c51e42fd82aff7cff017abbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":823,
                  "y":780},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u225.png"}},
{
          "id":"ee193869285e4309a1544397ac3b8aff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":853,
              "y":780},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6b1665cfa4d43b3a88a790c41240034",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":853,
                  "y":780},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/elefan/u225.png"}}]}},
  "masters":{
    "fdae7ed1a7a54530b5f4cecce3fbfa3f":{
      "packageId":"fdae7ed1a7a54530b5f4cecce3fbfa3f",
      "type":"Axure:Master",
      "name":"Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7a656bc70beb4cebbb674e1988d4ccb9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":650,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1550a7031d74549a5e3808fe28523dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":650,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"9a64193b359b4c5687c040ea64ab310a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":410,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5cfaf345bfe4457091303fdad238b98e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":410,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"c2fa319619ec41e39d10aee62ddb8138",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9d01a4d23d5b4b1fac75e0903a85807d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Catalog in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"catalog.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"0995ce6a56be4ebf8696cfcf5ca75c1f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD9E2EC},
              "location":{
                "x":70,
                "y":320},
              "size":{
                "width":820,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b06c0da3b5a94376a4702acc7e084e31",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD9E2EC},
                  "location":{
                    "x":70,
                    "y":320},
                  "size":{
                    "width":820,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u7.png"}},
{
            "id":"58d46532d08b497c90742a6a133b2265",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":150,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"65cd6803d6c74eada90e7cc5f192f6bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":150,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Catalog in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"catalog.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/buy/u9.png"}},
{
            "id":"68872e9f4165442ebcb39fe8fa985046",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":390,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d5698240ae0421e80a86a8b304f76f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":390,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u9.png"}},
{
            "id":"2745e76898374f108fd8cd9b8748526f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":630,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9e7abb7fc60344e497c13195a317e074",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":630,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u9.png"}},
{
            "id":"9e2c0346349c476bbc513a00520db92d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":342},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cedf53687e4e4ea191ef703b28181fd0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":342},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u15.png"}},
{
            "id":"1958f2ebcc884dbf835c764dd1e0632e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF14472,
                "opacity":1},
              "location":{
                "x":410,
                "y":14},
              "size":{
                "width":140,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"28c2a1a9c2754fb5bee218a2350f544e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF14472,
                    "opacity":1},
                  "location":{
                    "x":410,
                    "y":14},
                  "size":{
                    "width":140,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Elefan in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"elefan.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"095b25becc6a48e182e319ce869cfc12",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":394.5,
                "y":110},
              "size":{
                "width":171,
                "height":25}},
            "adaptiveStyles":{
},
            "images":{
              "normal~":"images/buy/u19_image_sketch.png",
              "disabled~":"images/buy/u19_disabled.png"}},
{
            "id":"f742296fd5ba4d319cc333eefe7c3860",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":110},
              "size":{
                "width":25,
                "height":25}},
            "adaptiveStyles":{
},
            "images":{
              "normal~":"images/elefan/u20_image_sketch.png",
              "disabled~":"images/elefan/u20_disabled.png"}},
{
            "id":"5688d6e12fca40bc82107435ade74fae",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":324,
                "y":70},
              "size":{
                "width":82,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"820ce519720c49cba7e04c3f8a67733a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":324,
                    "y":70},
                  "size":{
                    "width":82,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d52df4ad408c474184b0f50a9f5242c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":424,
                "y":70},
              "size":{
                "width":132,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c95cea01d0c542c38bb50a2ad316f282",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":424,
                    "y":70},
                  "size":{
                    "width":132,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Payment in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"payment.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7ba4c045bc86427bb3bec19d485445a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":566,
                "y":70},
              "size":{
                "width":70,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df3e28c35f4b4161b72bd4f4c99b9907",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":566,
                    "y":70},
                  "size":{
                    "width":70,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9d9b62fd3b5741d1a1de543a9481fbb4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":660,
                "y":26},
              "size":{
                "width":230,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fbcce5ff719d4a6ca2c0ffaf89f8c834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":660,
                    "y":26},
                  "size":{
                    "width":230,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f317dfa0e23f4065956c33d8c541073b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":28},
              "size":{
                "width":32,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3bb420b31ba44460b717cc338975b06e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":28},
                  "size":{
                    "width":32,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u29.png"}},
{
            "id":"2eaf40de2dee4350bde1920c18dcf0be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":132,
                "y":26},
              "size":{
                "width":148,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4debd93021d842c389c5c56e4e285d99",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":132,
                    "y":26},
                  "size":{
                    "width":148,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"55317add537e442a944eab57d304f251",
            "label":"bucket",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":132,
                "y":45},
              "size":{
                "width":148,
                "height":22}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Buy in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"buy.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"618cad80e4c7413b886dfb19397c0e88",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"07cb8e47c26449eab6398fef68b744cc",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "size":{
                        "width":148,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6f2f8cacfa564d7980a579bd3e51eae0",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "size":{
                            "width":148,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"ec420f32357c43588638318e77cbf9c3",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"c42d49c7a5e64de3a202859c73c0f28e",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true}},
                      "size":{
                        "width":200,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"87cac619af3942fea52b3708ecbb6b99",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true}},
                          "size":{
                            "width":200,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"8a2ddcc5c7ab48949481b5aa4fe4d4f4",
                "label":"State3",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"91fab3f4563942d6b71144d77106f702",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":2,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true}},
                      "size":{
                        "width":170,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a19d4903a0af403d8ef1ad6dac399ed0",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":2,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true}},
                          "size":{
                            "width":170,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Buy in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"buy.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"66356ebfc5724f5e91189b6b12d1f823",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF14472},
              "location":{
                "x":780,
                "y":65},
              "size":{
                "width":110,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68c4bb59bc7d4732b03fac8b416f2ef7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF14472},
                  "location":{
                    "x":780,
                    "y":65},
                  "size":{
                    "width":110,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/buy/u40.png"}},
{
            "id":"e8b19c5fda454c9ca3cf927e460b92e6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":750,
                "y":67.5},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fcb0a10c79542e989186966f18e915e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":750,
                    "y":67.5},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u42.png"}},
{
            "id":"b4310311897e4d5ca8d970a6a1d9bca7",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":750,
                "y":98},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9a4c6c85cec046d9885a64241e3adf32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":750,
                    "y":98},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u42.png"}},
{
            "id":"e96e115872054f0eb95247f17df8cd49",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "location":{
                "x":780,
                "y":100},
              "size":{
                "width":110,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cae4721a68664050ae415a7e4bfc6a21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "location":{
                    "x":780,
                    "y":100},
                  "size":{
                    "width":110,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "554cab938fd24941ba87a0ca1d2cdc87":{
      "scriptId":"u0",
      "7a656bc70beb4cebbb674e1988d4ccb9":{
        "scriptId":"u1"},
      "c1550a7031d74549a5e3808fe28523dc":{
        "scriptId":"u2"},
      "9a64193b359b4c5687c040ea64ab310a":{
        "scriptId":"u3"},
      "5cfaf345bfe4457091303fdad238b98e":{
        "scriptId":"u4"},
      "c2fa319619ec41e39d10aee62ddb8138":{
        "scriptId":"u5"},
      "9d01a4d23d5b4b1fac75e0903a85807d":{
        "scriptId":"u6"},
      "0995ce6a56be4ebf8696cfcf5ca75c1f":{
        "scriptId":"u7"},
      "b06c0da3b5a94376a4702acc7e084e31":{
        "scriptId":"u8"},
      "58d46532d08b497c90742a6a133b2265":{
        "scriptId":"u9"},
      "65cd6803d6c74eada90e7cc5f192f6bc":{
        "scriptId":"u10"},
      "68872e9f4165442ebcb39fe8fa985046":{
        "scriptId":"u11"},
      "8d5698240ae0421e80a86a8b304f76f3":{
        "scriptId":"u12"},
      "2745e76898374f108fd8cd9b8748526f":{
        "scriptId":"u13"},
      "9e7abb7fc60344e497c13195a317e074":{
        "scriptId":"u14"},
      "9e2c0346349c476bbc513a00520db92d":{
        "scriptId":"u15"},
      "cedf53687e4e4ea191ef703b28181fd0":{
        "scriptId":"u16"},
      "1958f2ebcc884dbf835c764dd1e0632e":{
        "scriptId":"u17"},
      "28c2a1a9c2754fb5bee218a2350f544e":{
        "scriptId":"u18"},
      "095b25becc6a48e182e319ce869cfc12":{
        "scriptId":"u19"},
      "f742296fd5ba4d319cc333eefe7c3860":{
        "scriptId":"u20"},
      "5688d6e12fca40bc82107435ade74fae":{
        "scriptId":"u21"},
      "820ce519720c49cba7e04c3f8a67733a":{
        "scriptId":"u22"},
      "d52df4ad408c474184b0f50a9f5242c2":{
        "scriptId":"u23"},
      "c95cea01d0c542c38bb50a2ad316f282":{
        "scriptId":"u24"},
      "7ba4c045bc86427bb3bec19d485445a2":{
        "scriptId":"u25"},
      "df3e28c35f4b4161b72bd4f4c99b9907":{
        "scriptId":"u26"},
      "9d9b62fd3b5741d1a1de543a9481fbb4":{
        "scriptId":"u27"},
      "fbcce5ff719d4a6ca2c0ffaf89f8c834":{
        "scriptId":"u28"},
      "f317dfa0e23f4065956c33d8c541073b":{
        "scriptId":"u29"},
      "3bb420b31ba44460b717cc338975b06e":{
        "scriptId":"u30"},
      "2eaf40de2dee4350bde1920c18dcf0be":{
        "scriptId":"u31"},
      "4debd93021d842c389c5c56e4e285d99":{
        "scriptId":"u32"},
      "55317add537e442a944eab57d304f251":{
        "scriptId":"u33"},
      "07cb8e47c26449eab6398fef68b744cc":{
        "scriptId":"u34"},
      "6f2f8cacfa564d7980a579bd3e51eae0":{
        "scriptId":"u35"},
      "c42d49c7a5e64de3a202859c73c0f28e":{
        "scriptId":"u36"},
      "87cac619af3942fea52b3708ecbb6b99":{
        "scriptId":"u37"},
      "91fab3f4563942d6b71144d77106f702":{
        "scriptId":"u38"},
      "a19d4903a0af403d8ef1ad6dac399ed0":{
        "scriptId":"u39"},
      "66356ebfc5724f5e91189b6b12d1f823":{
        "scriptId":"u40"},
      "68c4bb59bc7d4732b03fac8b416f2ef7":{
        "scriptId":"u41"},
      "e8b19c5fda454c9ca3cf927e460b92e6":{
        "scriptId":"u42"},
      "6fcb0a10c79542e989186966f18e915e":{
        "scriptId":"u43"},
      "b4310311897e4d5ca8d970a6a1d9bca7":{
        "scriptId":"u44"},
      "9a4c6c85cec046d9885a64241e3adf32":{
        "scriptId":"u45"},
      "e96e115872054f0eb95247f17df8cd49":{
        "scriptId":"u46"},
      "cae4721a68664050ae415a7e4bfc6a21":{
        "scriptId":"u47"}},
    "830f6a44e5894f19be6af482e54ff6b7":{
      "scriptId":"u48"},
    "ce4d32935337479291854abc5b8aa7f7":{
      "scriptId":"u49"},
    "df42d89f9b7d401f95dfe734bbed2399":{
      "scriptId":"u50"},
    "2306fbc5269f40fd9faadfc887d0953c":{
      "scriptId":"u51"},
    "4c4fb594aba346cd8375e6ab9de6f714":{
      "scriptId":"u52"},
    "83d48472711044f0b459debaed55bbaa":{
      "scriptId":"u53"},
    "4c0ad707bf8e486c8e73185ef059f486":{
      "scriptId":"u54"},
    "11e918baecf340e8b7c8f961b22c3a69":{
      "scriptId":"u55"},
    "97973b67f8ae45e0aa379c7e6ce744a0":{
      "scriptId":"u56"},
    "88b41f6ab1ef45c29ce66f66d57b5be3":{
      "scriptId":"u57"},
    "abd46bd4b4234c0dbeba39a927d4ba82":{
      "scriptId":"u58"},
    "b37abe3dedd644e4b24b61a22044cd36":{
      "scriptId":"u59"},
    "438206a879c14fb0bd3e878e165069e8":{
      "scriptId":"u60"},
    "fbfd5e6f987644389df9ae31eb48fb35":{
      "scriptId":"u61"},
    "134b45c1c09f4c90ac4ffa307f1ea6a7":{
      "scriptId":"u62"},
    "15916a1ceaf748219816ffa217735e7c":{
      "scriptId":"u63"},
    "f3e46b24841c406aae6303b1a5638bea":{
      "scriptId":"u64"},
    "551a5037a215461b84cf13522596d046":{
      "scriptId":"u65"},
    "53acb3668fe0491692c20a6b316b51d7":{
      "scriptId":"u66"},
    "951ac30ef3944cee9efc860d4d4b4d9f":{
      "scriptId":"u67"},
    "4934be60ccb54fe4a6ef7addbe3f7af2":{
      "scriptId":"u68"},
    "619d8227db5541cab8593a2a86f6e609":{
      "scriptId":"u69"},
    "9aeb82b87c2447fea6ea550d6e30e16e":{
      "scriptId":"u70"},
    "acc1d7ad13654721bb90251a286f1fb4":{
      "scriptId":"u71"},
    "d2aa687fe62f44029c477e0a93ff29ac":{
      "scriptId":"u72"},
    "fd1ac9fdc3f04caa939a60dd418f0381":{
      "scriptId":"u73"},
    "72c6fda1fd10497cbe45d652097bfc22":{
      "scriptId":"u74"},
    "e5ef40601bb14748abe120e8f8bfea91":{
      "scriptId":"u75"},
    "62e639c783a44b51b13f8238c89b14ce":{
      "scriptId":"u76"},
    "39abc06b618a453bafc536d404e4a7fe":{
      "scriptId":"u77"},
    "fa461fa04da34dcb976f85881811ddd1":{
      "scriptId":"u78"},
    "996158340d3545f1adf2b098c58039b9":{
      "scriptId":"u79"},
    "12ae9bbe502e4583bd36dbdf998292eb":{
      "scriptId":"u80"},
    "0999a9da0ba5432b9faa70972d819f0f":{
      "scriptId":"u81"},
    "41d2b7aa4ba44a0ca1753aae92f8836c":{
      "scriptId":"u82"},
    "b65f7a1fca564044be443141f6962412":{
      "scriptId":"u83"},
    "3e32444706b64f0fbe35f260f12cc8cd":{
      "scriptId":"u84"},
    "9893e2c07fcd4d52a67afb66fac455bf":{
      "scriptId":"u85"},
    "b8b211fbec2c4aaba7ba76744b02ea34":{
      "scriptId":"u86"},
    "46a92597f4fd44afaa7ca23fb078dbdc":{
      "scriptId":"u87"},
    "4a03984d5bc345189096a9307fc6286b":{
      "scriptId":"u88"},
    "0c8f4fc97c174e99b8c691554d6eec64":{
      "scriptId":"u89"},
    "5c1e56abf6ad42c6b3fdd6c0097ccdad":{
      "scriptId":"u90"},
    "c05a08ccfc65405d984e243ef954a7e6":{
      "scriptId":"u91"},
    "7639c4f6ad19466a911ca4fc12f2c01a":{
      "scriptId":"u92"},
    "3c81fdaa3b7d4156b9b4163e09966db8":{
      "scriptId":"u93"},
    "b3c4b55cdfc3494380980956c19b4c8a":{
      "scriptId":"u94"},
    "8509e83b853d4e43a6055cc57898b137":{
      "scriptId":"u95"},
    "21cbb0f837fe402faa95f77a072be264":{
      "scriptId":"u96"},
    "91147b39515742778c7538a48d8bf1a7":{
      "scriptId":"u97"},
    "d7610835c51e42fd82aff7cff017abbb":{
      "scriptId":"u98"},
    "ee193869285e4309a1544397ac3b8aff":{
      "scriptId":"u99"},
    "b6b1665cfa4d43b3a88a790c41240034":{
      "scriptId":"u100"}}});