$axure.loadCurrentPage({
  "url":"about.html",
  "generationDate":new Date(1409664627971.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b81529ae235240c1b0ed6d92760a9e4b",
    "type":"Axure:Page",
    "name":"About",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"30",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2361d28d20934b92bb80ce1c340591a9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fdae7ed1a7a54530b5f4cecce3fbfa3f"},
{
          "id":"783fa366c7e24f79aeee2ea87dce572d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF768FA8,
              "opacity":1},
            "location":{
              "x":70,
              "y":476},
            "size":{
              "width":820,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f013672bc674be8a57b5f7def4d1e5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF768FA8,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":476},
                "size":{
                  "width":820,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91aec180031442c894c622a3452f174c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":1114}},
          "adaptiveStyles":{
},
          "masterId":"74ebfe1a9ef6482fb77fdeca92c9fee2"},
{
          "id":"5503eee1fc9d4ccd9f15a2bab2dfaddb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0080,
              "opacity":1},
            "location":{
              "x":288,
              "y":422},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8997b40c484f41eaa546bfc27bd37b69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0080,
                  "opacity":1},
                "location":{
                  "x":288,
                  "y":422},
                "size":{
                  "width":145,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe7b55a995cf40c9a10843b5a8a6a20a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Tahoma Обычный', 'Tahoma'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF91ABC8,
              "opacity":1},
            "location":{
              "x":72,
              "y":427},
            "size":{
              "width":184,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1021b1dec6274affb2318f1898fcbb50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Tahoma Обычный', 'Tahoma'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF91ABC8,
                  "opacity":1},
                "location":{
                  "x":72,
                  "y":427},
                "size":{
                  "width":184,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"daf6a2c460f84130a375633109e95c3b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":430},
            "size":{
              "width":16,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u96_line.png"}}]}},
  "masters":{
    "fdae7ed1a7a54530b5f4cecce3fbfa3f":{
      "packageId":"fdae7ed1a7a54530b5f4cecce3fbfa3f",
      "type":"Axure:Master",
      "name":"Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7a656bc70beb4cebbb674e1988d4ccb9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":650,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1550a7031d74549a5e3808fe28523dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":650,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"9a64193b359b4c5687c040ea64ab310a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":410,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5cfaf345bfe4457091303fdad238b98e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":410,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"c2fa319619ec41e39d10aee62ddb8138",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":180},
              "size":{
                "width":140,
                "height":130}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9d01a4d23d5b4b1fac75e0903a85807d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":180},
                  "size":{
                    "width":140,
                    "height":130}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"linkWindow",
                        "description":"Open Catalog in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"catalog.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/elefan/u1.png"}},
{
            "id":"0995ce6a56be4ebf8696cfcf5ca75c1f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFD9E2EC},
              "location":{
                "x":70,
                "y":320},
              "size":{
                "width":820,
                "height":70}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b06c0da3b5a94376a4702acc7e084e31",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD9E2EC},
                  "location":{
                    "x":70,
                    "y":320},
                  "size":{
                    "width":820,
                    "height":70}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/about/u7.png"}},
{
            "id":"58d46532d08b497c90742a6a133b2265",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":150,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"65cd6803d6c74eada90e7cc5f192f6bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":150,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Catalog in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"catalog.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/about/u9.png"}},
{
            "id":"68872e9f4165442ebcb39fe8fa985046",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":390,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d5698240ae0421e80a86a8b304f76f3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":390,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/about/u9.png"}},
{
            "id":"2745e76898374f108fd8cd9b8748526f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":630,
                "y":330},
              "size":{
                "width":180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9e7abb7fc60344e497c13195a317e074",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":630,
                    "y":330},
                  "size":{
                    "width":180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/about/u9.png"}},
{
            "id":"9e2c0346349c476bbc513a00520db92d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":342},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cedf53687e4e4ea191ef703b28181fd0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":342},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u15.png"}},
{
            "id":"1958f2ebcc884dbf835c764dd1e0632e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFF14472,
                "opacity":1},
              "location":{
                "x":410,
                "y":14},
              "size":{
                "width":140,
                "height":36}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"28c2a1a9c2754fb5bee218a2350f544e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"center",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFF14472,
                    "opacity":1},
                  "location":{
                    "x":410,
                    "y":14},
                  "size":{
                    "width":140,
                    "height":36}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Elefan in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"elefan.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"095b25becc6a48e182e319ce869cfc12",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":394.5,
                "y":110},
              "size":{
                "width":171,
                "height":25}},
            "adaptiveStyles":{
},
            "images":{
              "normal~":"images/about/u19_image_sketch.png",
              "disabled~":"images/about/u19_disabled.png"}},
{
            "id":"f742296fd5ba4d319cc333eefe7c3860",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":540,
                "y":110},
              "size":{
                "width":25,
                "height":25}},
            "adaptiveStyles":{
},
            "images":{
              "normal~":"images/elefan/u20_image_sketch.png",
              "disabled~":"images/elefan/u20_disabled.png"}},
{
            "id":"5688d6e12fca40bc82107435ade74fae",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":324,
                "y":70},
              "size":{
                "width":82,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"820ce519720c49cba7e04c3f8a67733a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":324,
                    "y":70},
                  "size":{
                    "width":82,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d52df4ad408c474184b0f50a9f5242c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":424,
                "y":70},
              "size":{
                "width":132,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c95cea01d0c542c38bb50a2ad316f282",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":424,
                    "y":70},
                  "size":{
                    "width":132,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Payment in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"payment.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7ba4c045bc86427bb3bec19d485445a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":566,
                "y":70},
              "size":{
                "width":70,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df3e28c35f4b4161b72bd4f4c99b9907",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":566,
                    "y":70},
                  "size":{
                    "width":70,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9d9b62fd3b5741d1a1de543a9481fbb4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":660,
                "y":26},
              "size":{
                "width":230,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fbcce5ff719d4a6ca2c0ffaf89f8c834",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":660,
                    "y":26},
                  "size":{
                    "width":230,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f317dfa0e23f4065956c33d8c541073b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":28},
              "size":{
                "width":32,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3bb420b31ba44460b717cc338975b06e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":28},
                  "size":{
                    "width":32,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u29.png"}},
{
            "id":"2eaf40de2dee4350bde1920c18dcf0be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":132,
                "y":26},
              "size":{
                "width":148,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4debd93021d842c389c5c56e4e285d99",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":132,
                    "y":26},
                  "size":{
                    "width":148,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"55317add537e442a944eab57d304f251",
            "label":"bucket",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":132,
                "y":45},
              "size":{
                "width":148,
                "height":22}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Buy in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"buy.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"618cad80e4c7413b886dfb19397c0e88",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"07cb8e47c26449eab6398fef68b744cc",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "size":{
                        "width":148,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6f2f8cacfa564d7980a579bd3e51eae0",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "size":{
                            "width":148,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"ec420f32357c43588638318e77cbf9c3",
                "label":"State2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"c42d49c7a5e64de3a202859c73c0f28e",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":1,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true}},
                      "size":{
                        "width":200,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"87cac619af3942fea52b3708ecbb6b99",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":1,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true}},
                          "size":{
                            "width":200,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}},
{
                "id":"8a2ddcc5c7ab48949481b5aa4fe4d4f4",
                "label":"State3",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"91fab3f4563942d6b71144d77106f702",
                    "label":"",
                    "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                    "panelIndex":2,
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Tahoma Oblique', 'Tahoma'",
                      "fontSize":"14px",
                      "fontStyle":"oblique",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFF14472,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true}},
                      "size":{
                        "width":170,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a19d4903a0af403d8ef1ad6dac399ed0",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"55317add537e442a944eab57d304f251",
                        "panelIndex":2,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Tahoma Oblique', 'Tahoma'",
                          "fontSize":"14px",
                          "fontStyle":"oblique",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF14472,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true}},
                          "size":{
                            "width":170,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Buy in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"buy.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"66356ebfc5724f5e91189b6b12d1f823",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF14472},
              "location":{
                "x":780,
                "y":65},
              "size":{
                "width":110,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68c4bb59bc7d4732b03fac8b416f2ef7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF14472},
                  "location":{
                    "x":780,
                    "y":65},
                  "size":{
                    "width":110,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/about/u40.png"}},
{
            "id":"e8b19c5fda454c9ca3cf927e460b92e6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":750,
                "y":67.5},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fcb0a10c79542e989186966f18e915e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":750,
                    "y":67.5},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u42.png"}},
{
            "id":"b4310311897e4d5ca8d970a6a1d9bca7",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":750,
                "y":98},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9a4c6c85cec046d9885a64241e3adf32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":750,
                    "y":98},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u42.png"}},
{
            "id":"e96e115872054f0eb95247f17df8cd49",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "horizontalAlignment":"center",
              "location":{
                "x":780,
                "y":100},
              "size":{
                "width":110,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cae4721a68664050ae415a7e4bfc6a21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"center",
                  "location":{
                    "x":780,
                    "y":100},
                  "size":{
                    "width":110,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "74ebfe1a9ef6482fb77fdeca92c9fee2":{
      "packageId":"74ebfe1a9ef6482fb77fdeca92c9fee2",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b1b0b8a6b1614fe4adefa6afeb9f7654",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":72,
                "y":1560},
              "size":{
                "width":818,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/about/u51_line.png"}},
{
            "id":"2c1eacc22d06425b9261c1f8054eac44",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Oblique', 'Tahoma'",
              "fontStyle":"oblique",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0080,
                "opacity":1},
              "location":{
                "x":72,
                "y":1534},
              "size":{
                "width":68,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1137be7b0dfa48de81789eb988fc3c56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Oblique', 'Tahoma'",
                  "fontStyle":"oblique",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0080,
                    "opacity":1},
                  "location":{
                    "x":72,
                    "y":1534},
                  "size":{
                    "width":68,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2f256728abca4bdc9e257a7f82e69239",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Oblique', 'Tahoma'",
              "fontStyle":"oblique",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0080,
                "opacity":1},
              "location":{
                "x":160,
                "y":1534},
              "size":{
                "width":112,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1296028ff3ea42ef8a46311c7a7ca77e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Oblique', 'Tahoma'",
                  "fontStyle":"oblique",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0080,
                    "opacity":1},
                  "location":{
                    "x":160,
                    "y":1534},
                  "size":{
                    "width":112,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Payment in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"payment.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f1b2eb7af9b74068b753fc76088291ae",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Oblique', 'Tahoma'",
              "fontStyle":"oblique",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0080,
                "opacity":1},
              "location":{
                "x":290,
                "y":1534},
              "size":{
                "width":56,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b6696d14addd48c6a2dede209b7209ce",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Oblique', 'Tahoma'",
                  "fontStyle":"oblique",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0080,
                    "opacity":1},
                  "location":{
                    "x":290,
                    "y":1534},
                  "size":{
                    "width":56,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contacts in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contacts.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5c60756c8a4c4a28a901d51b67281cf6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":660,
                "y":1534},
              "size":{
                "width":230,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c9ae06db76145f291c0695ac915b1fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":660,
                    "y":1534},
                  "size":{
                    "width":230,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7c61452fc67143f6b80cde64aae46c3a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "location":{
                "x":72,
                "y":1580},
              "size":{
                "width":296,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f222802c9c9d41afbe470aeefa83c0f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "location":{
                    "x":72,
                    "y":1580},
                  "size":{
                    "width":296,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2d0c2bcfc7274e198e6404e21fed6964",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"right",
              "location":{
                "x":660,
                "y":1580},
              "size":{
                "width":230,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"08c0a6e3b7d147c182676dc9f06d87fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"right",
                  "location":{
                    "x":660,
                    "y":1580},
                  "size":{
                    "width":230,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4819caada25b4eb4b689ad20bcd8f10a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":474,
                "y":1363},
              "size":{
                "width":46,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"96c69331382e4da4a90cb1f85b344c98",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":474,
                    "y":1363},
                  "size":{
                    "width":46,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"caf0ba6132a249d3ac50671a9c8685eb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":90,
                "y":1420},
              "size":{
                "width":134,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"36189d7ba0d64cb9a0a07515d496c607",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":90,
                    "y":1420},
                  "size":{
                    "width":134,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"35e5d18d952c4a3a8917f2cb01780a03",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":1450},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a87253ad42fa45cba6ae39696f4ddcdf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":90,
                    "y":1450},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u211.png"}},
{
            "id":"00e3ee0e3aa84c7fa457bfe1feab1e2f",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":1450},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0d436964b445401cb71d562d7efc67e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":140,
                    "y":1450},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u211.png"}},
{
            "id":"6d2d9dbe667543fbb47670b2d492741e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":1450},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a33cfb19f46e4c7cbffb06abbacc349a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":1450},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u211.png"}},
{
            "id":"b54b86a03a084da496526bcec9b25f35",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":240,
                "y":1450},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f03721ce13b04231904f6a5b4858b47e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":240,
                    "y":1450},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u211.png"}},
{
            "id":"b07b6716d51b4d48b55d37847096a921",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0080,
                "opacity":1},
              "location":{
                "x":384,
                "y":1420},
              "size":{
                "width":210,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2e6ff2e6cac447399e5b6ed95dabd027",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0080,
                    "opacity":1},
                  "location":{
                    "x":384,
                    "y":1420},
                  "size":{
                    "width":210,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"da588011bb8a43359bb12ddd62312d4a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Tahoma Обычный', 'Tahoma'",
              "horizontalAlignment":"right",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF768FA8,
                "opacity":1},
              "location":{
                "x":734,
                "y":1420},
              "size":{
                "width":140,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a270eefe6857466c80339eb0e42fb992",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Tahoma Обычный', 'Tahoma'",
                  "horizontalAlignment":"right",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF768FA8,
                    "opacity":1},
                  "location":{
                    "x":734,
                    "y":1420},
                  "size":{
                    "width":140,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"da2e74a80a454edbbb2506211e775856",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":389,
                "y":1457.5},
              "size":{
                "width":200,
                "height":25}},
            "adaptiveStyles":{
},
            "images":{
              "normal~":"images/about/u80_image_sketch.png",
              "disabled~":"images/about/u80_disabled.png"}},
{
            "id":"ab41fb740c5b4920914a440eb09288c4",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":566,
                "y":1457.5},
              "size":{
                "width":28,
                "height":25}},
            "adaptiveStyles":{
},
            "images":{
              "normal~":"images/elefan/u224_image_sketch.png",
              "disabled~":"images/elefan/u224_disabled.png"}},
{
            "id":"128baf917b584de499be7aa555ada9ac",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":734,
                "y":1460},
              "size":{
                "width":21,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e6ad43b1a2de48cb8b789ce9159d2e86",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":734,
                    "y":1460},
                  "size":{
                    "width":21,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u225.png"}},
{
            "id":"abec2f9613274a7d988ede16712acfc1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":764,
                "y":1460},
              "size":{
                "width":21,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ec904bf1c6cc4eeda6bfb3249ab01e45",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":764,
                    "y":1460},
                  "size":{
                    "width":21,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u225.png"}},
{
            "id":"8469fdc94cee4760bf0f3ad6dcbcf3d2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":793,
                "y":1460},
              "size":{
                "width":21,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0f3c1832c4124ca38cfa4ceaff3d77ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":793,
                    "y":1460},
                  "size":{
                    "width":21,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u225.png"}},
{
            "id":"74514e89534745e480d78849f5ebd298",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":823,
                "y":1460},
              "size":{
                "width":21,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fd6f4aa900d94e6583f1399a95c4d065",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":823,
                    "y":1460},
                  "size":{
                    "width":21,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u225.png"}},
{
            "id":"892b7f3c1bd443288cbc7fd3f1e7d465",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":853,
                "y":1460},
              "size":{
                "width":21,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94c40365c1744c1fab4f11fd87ccc073",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":853,
                    "y":1460},
                  "size":{
                    "width":21,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/elefan/u225.png"}}]}}},
  "objectPaths":{
    "2361d28d20934b92bb80ce1c340591a9":{
      "scriptId":"u0",
      "7a656bc70beb4cebbb674e1988d4ccb9":{
        "scriptId":"u1"},
      "c1550a7031d74549a5e3808fe28523dc":{
        "scriptId":"u2"},
      "9a64193b359b4c5687c040ea64ab310a":{
        "scriptId":"u3"},
      "5cfaf345bfe4457091303fdad238b98e":{
        "scriptId":"u4"},
      "c2fa319619ec41e39d10aee62ddb8138":{
        "scriptId":"u5"},
      "9d01a4d23d5b4b1fac75e0903a85807d":{
        "scriptId":"u6"},
      "0995ce6a56be4ebf8696cfcf5ca75c1f":{
        "scriptId":"u7"},
      "b06c0da3b5a94376a4702acc7e084e31":{
        "scriptId":"u8"},
      "58d46532d08b497c90742a6a133b2265":{
        "scriptId":"u9"},
      "65cd6803d6c74eada90e7cc5f192f6bc":{
        "scriptId":"u10"},
      "68872e9f4165442ebcb39fe8fa985046":{
        "scriptId":"u11"},
      "8d5698240ae0421e80a86a8b304f76f3":{
        "scriptId":"u12"},
      "2745e76898374f108fd8cd9b8748526f":{
        "scriptId":"u13"},
      "9e7abb7fc60344e497c13195a317e074":{
        "scriptId":"u14"},
      "9e2c0346349c476bbc513a00520db92d":{
        "scriptId":"u15"},
      "cedf53687e4e4ea191ef703b28181fd0":{
        "scriptId":"u16"},
      "1958f2ebcc884dbf835c764dd1e0632e":{
        "scriptId":"u17"},
      "28c2a1a9c2754fb5bee218a2350f544e":{
        "scriptId":"u18"},
      "095b25becc6a48e182e319ce869cfc12":{
        "scriptId":"u19"},
      "f742296fd5ba4d319cc333eefe7c3860":{
        "scriptId":"u20"},
      "5688d6e12fca40bc82107435ade74fae":{
        "scriptId":"u21"},
      "820ce519720c49cba7e04c3f8a67733a":{
        "scriptId":"u22"},
      "d52df4ad408c474184b0f50a9f5242c2":{
        "scriptId":"u23"},
      "c95cea01d0c542c38bb50a2ad316f282":{
        "scriptId":"u24"},
      "7ba4c045bc86427bb3bec19d485445a2":{
        "scriptId":"u25"},
      "df3e28c35f4b4161b72bd4f4c99b9907":{
        "scriptId":"u26"},
      "9d9b62fd3b5741d1a1de543a9481fbb4":{
        "scriptId":"u27"},
      "fbcce5ff719d4a6ca2c0ffaf89f8c834":{
        "scriptId":"u28"},
      "f317dfa0e23f4065956c33d8c541073b":{
        "scriptId":"u29"},
      "3bb420b31ba44460b717cc338975b06e":{
        "scriptId":"u30"},
      "2eaf40de2dee4350bde1920c18dcf0be":{
        "scriptId":"u31"},
      "4debd93021d842c389c5c56e4e285d99":{
        "scriptId":"u32"},
      "55317add537e442a944eab57d304f251":{
        "scriptId":"u33"},
      "07cb8e47c26449eab6398fef68b744cc":{
        "scriptId":"u34"},
      "6f2f8cacfa564d7980a579bd3e51eae0":{
        "scriptId":"u35"},
      "c42d49c7a5e64de3a202859c73c0f28e":{
        "scriptId":"u36"},
      "87cac619af3942fea52b3708ecbb6b99":{
        "scriptId":"u37"},
      "91fab3f4563942d6b71144d77106f702":{
        "scriptId":"u38"},
      "a19d4903a0af403d8ef1ad6dac399ed0":{
        "scriptId":"u39"},
      "66356ebfc5724f5e91189b6b12d1f823":{
        "scriptId":"u40"},
      "68c4bb59bc7d4732b03fac8b416f2ef7":{
        "scriptId":"u41"},
      "e8b19c5fda454c9ca3cf927e460b92e6":{
        "scriptId":"u42"},
      "6fcb0a10c79542e989186966f18e915e":{
        "scriptId":"u43"},
      "b4310311897e4d5ca8d970a6a1d9bca7":{
        "scriptId":"u44"},
      "9a4c6c85cec046d9885a64241e3adf32":{
        "scriptId":"u45"},
      "e96e115872054f0eb95247f17df8cd49":{
        "scriptId":"u46"},
      "cae4721a68664050ae415a7e4bfc6a21":{
        "scriptId":"u47"}},
    "783fa366c7e24f79aeee2ea87dce572d":{
      "scriptId":"u48"},
    "7f013672bc674be8a57b5f7def4d1e5a":{
      "scriptId":"u49"},
    "91aec180031442c894c622a3452f174c":{
      "scriptId":"u50",
      "b1b0b8a6b1614fe4adefa6afeb9f7654":{
        "scriptId":"u51"},
      "2c1eacc22d06425b9261c1f8054eac44":{
        "scriptId":"u52"},
      "1137be7b0dfa48de81789eb988fc3c56":{
        "scriptId":"u53"},
      "2f256728abca4bdc9e257a7f82e69239":{
        "scriptId":"u54"},
      "1296028ff3ea42ef8a46311c7a7ca77e":{
        "scriptId":"u55"},
      "f1b2eb7af9b74068b753fc76088291ae":{
        "scriptId":"u56"},
      "b6696d14addd48c6a2dede209b7209ce":{
        "scriptId":"u57"},
      "5c60756c8a4c4a28a901d51b67281cf6":{
        "scriptId":"u58"},
      "7c9ae06db76145f291c0695ac915b1fb":{
        "scriptId":"u59"},
      "7c61452fc67143f6b80cde64aae46c3a":{
        "scriptId":"u60"},
      "f222802c9c9d41afbe470aeefa83c0f9":{
        "scriptId":"u61"},
      "2d0c2bcfc7274e198e6404e21fed6964":{
        "scriptId":"u62"},
      "08c0a6e3b7d147c182676dc9f06d87fd":{
        "scriptId":"u63"},
      "4819caada25b4eb4b689ad20bcd8f10a":{
        "scriptId":"u64"},
      "96c69331382e4da4a90cb1f85b344c98":{
        "scriptId":"u65"},
      "caf0ba6132a249d3ac50671a9c8685eb":{
        "scriptId":"u66"},
      "36189d7ba0d64cb9a0a07515d496c607":{
        "scriptId":"u67"},
      "35e5d18d952c4a3a8917f2cb01780a03":{
        "scriptId":"u68"},
      "a87253ad42fa45cba6ae39696f4ddcdf":{
        "scriptId":"u69"},
      "00e3ee0e3aa84c7fa457bfe1feab1e2f":{
        "scriptId":"u70"},
      "0d436964b445401cb71d562d7efc67e7":{
        "scriptId":"u71"},
      "6d2d9dbe667543fbb47670b2d492741e":{
        "scriptId":"u72"},
      "a33cfb19f46e4c7cbffb06abbacc349a":{
        "scriptId":"u73"},
      "b54b86a03a084da496526bcec9b25f35":{
        "scriptId":"u74"},
      "f03721ce13b04231904f6a5b4858b47e":{
        "scriptId":"u75"},
      "b07b6716d51b4d48b55d37847096a921":{
        "scriptId":"u76"},
      "2e6ff2e6cac447399e5b6ed95dabd027":{
        "scriptId":"u77"},
      "da588011bb8a43359bb12ddd62312d4a":{
        "scriptId":"u78"},
      "a270eefe6857466c80339eb0e42fb992":{
        "scriptId":"u79"},
      "da2e74a80a454edbbb2506211e775856":{
        "scriptId":"u80"},
      "ab41fb740c5b4920914a440eb09288c4":{
        "scriptId":"u81"},
      "128baf917b584de499be7aa555ada9ac":{
        "scriptId":"u82"},
      "e6ad43b1a2de48cb8b789ce9159d2e86":{
        "scriptId":"u83"},
      "abec2f9613274a7d988ede16712acfc1":{
        "scriptId":"u84"},
      "ec904bf1c6cc4eeda6bfb3249ab01e45":{
        "scriptId":"u85"},
      "8469fdc94cee4760bf0f3ad6dcbcf3d2":{
        "scriptId":"u86"},
      "0f3c1832c4124ca38cfa4ceaff3d77ae":{
        "scriptId":"u87"},
      "74514e89534745e480d78849f5ebd298":{
        "scriptId":"u88"},
      "fd6f4aa900d94e6583f1399a95c4d065":{
        "scriptId":"u89"},
      "892b7f3c1bd443288cbc7fd3f1e7d465":{
        "scriptId":"u90"},
      "94c40365c1744c1fab4f11fd87ccc073":{
        "scriptId":"u91"}},
    "5503eee1fc9d4ccd9f15a2bab2dfaddb":{
      "scriptId":"u92"},
    "8997b40c484f41eaa546bfc27bd37b69":{
      "scriptId":"u93"},
    "fe7b55a995cf40c9a10843b5a8a6a20a":{
      "scriptId":"u94"},
    "1021b1dec6274affb2318f1898fcbb50":{
      "scriptId":"u95"},
    "daf6a2c460f84130a375633109e95c3b":{
      "scriptId":"u96"}}});